[Interface]
Address = 10.44.105.1/32
PrivateKey = 2HDA9gPXG8n/yBxu4wBxF3UN0e5XmjjozeqQC6UPqHQ=
MTU = 1300

[Peer]
PublicKey = ygRKQWr26jpK4F4L3b8vvnwgyIjM2YuYpOr0KdNRSSQ=
Endpoint = 91.98.148.200:51820
AllowedIPs = 10.44.0.0/16, 91.98.46.45/32
PersistentKeepalive = 5
